export const GET_PLACARDS = 'GET_PLACARDS';
export const ADD_PLACARD = 'ADD_PLACARD';
export const DELETE_PLACARD = 'DELETE_PLACARD';
export const UPDATE_PLACARD = 'UPDATE_PLACARD';
export const FILTER_PLACARDS = 'FILTER_PLACARDS';
export const CLEAR_PLACARDS = 'CLEAR_PLACARDS';
